### ISSUE TITLE
while running test.py(RuntimeError: CUDA out of memory)

### ISSUE THREAD

**Issue by HacxS** [Maclory/Deep-Iterative-Collaboration#20]
![image](https://user-images.githubusercontent.com/39330483/93207310-69b7a280-f778-11ea-8978-a88342c133a2.png)

**Help Please**

  0%|                                                                                                                                                                | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test.py", line 128, in <module>
    main()
  File "test.py", line 69, in main
    solver.test()
  File "/home/govind/audio-video/image-enhance/Deep-Iterative-Collaboration/code/solvers/SRLandmarkGANSolver.py", line 220, in test
    SR_list, heatmap_list = forward_func(self.LR)
  File "/home/govind/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/govind/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/govind/audio-video/image-enhance/Deep-Iterative-Collaboration/code/networks/dic_arch.py", line 89, in forward
    FB_out_first = self.first_block(x)
  File "/home/govind/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/govind/audio-video/image-enhance/Deep-Iterative-Collaboration/code/networks/srfbn_hg_arch.py", line 130, in forward
    LD_H = self.downtranBlocks[idx-1](LD_H)
  File "/home/govind/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/govind/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/govind/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/govind/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/govind/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 3.00 GiB (GPU 0; 15.90 GiB total capacity; 12.32 GiB already allocated; 2.86 GiB free; 12.34 GiB reserved in total by PyTorch)

and current configurations:
{
    "name": "CelebA_GAN",
    "mode": "sr_align_gan",
    "degradation": "BI",
    "gpu_ids": [0],
    "use_tb_logger": false,
    "scale": 8,
    "is_train": false,
    "rgb_range": 1,
    "save_image": true,
    "datasets": {
        "test_CelebA": {
            "mode": "LRHR",
            "name": "CelebA",
            "dataroot_HR": "/home/govind/audio-video/image-enhance/Deep-Iterative-Collaboration/image/",
            "dataroot_LR": "/home/govind/audio-video/image-enhance/Deep-Iterative-Collaboration/image/", **single image inside**
            "data_type": "img",
            "LR_size": 16,
            "HR_size": 128
        }
    },
    "networks": {
        "which_model": "DIC",
        "num_features": 48,
        "in_channels": 3,
        "out_channels": 3,
        "num_steps": 4,
        "num_groups": 6,
        "detach_attention": false,
        "hg_num_feature": 256,
        "hg_num_keypoints": 68,
        "num_fusion_block": 7
    },
    "solver": {
        "pretrained_path": "/home/govind/audio-video/image-enhance/Deep-Iterative-Collaboration/models/DICGAN_CelebA.pth"
    },
    "path": {
      "root": "../"
    }
}

**Comment by forMUmu** [comment]
How to do? I have got this problem. I don't know how to solve it.

**Comment by malinjie-hub** [comment]
I have got this problem too，Hope to get help
